name: Release when tagged

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.ADML'
      - '**.ADMX'
      - '**.ico'
      - '**.reg'
      - '**.yml'
    tags:
      - "*.*.*"

  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.ADML'
      - '**.ADMX'
      - '**.ico'
      - '**.reg'
      - '**.yml'
jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Wix
        uses: actions/checkout@v4
        with:
          repository: fbarresi/wix
          path: wix

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Restore and publish main project
        run: |
          msbuild IntegrityService\IntegrityService.csproj /t:restore /t:publish /p:Configuration=Release /p:SelfContained=true /p:RuntimeIdentifier=win-x64 /p:PublishsingleFile=true
          New-Item -ItemType Directory -Name D:\a\IntegrityService\IntegrityService\publish\ -Force -Confirm:$false
          Copy-Item -Path ".\IntegrityService\bin\Release\net8.0-windows10.0.17763.0\win-x64\publish\IntegrityService.exe" -Destination D:\a\IntegrityService\IntegrityService\publish\ -Verbose

      - name: Enumerate root folder
        shell: powershell
        run: ls -r

      - name: Build installer
        run: |
          $source = (Get-Item (Get-Location)).FullName
          $source
          wix\tools\candle.exe "IntegrityService.Installer\Product.wxs" -out "$source\obj\Product.wixobj" -nologo -arch x86 -ext WixUtilExtension -fips -pedantic -v       
          ls -r
          cd IntegrityService.Installer
          &"$source\wix\tools\Light.exe" "$source\obj\Product.wixobj" -nologo -out $source\publish\IntegrityService.Installer.msi -ext WixUtilExtension -pdbout $source\publish\IntegrityService.Installer.wixpdb -cultures:null -spdb -contentsfile $source\obj\IntegrityService.Installer.wixproj.BindContentsFileListnull.txt -outputsfile $source\obj\IntegrityService.Installer.wixproj.BindOutputsFileListnull.txt -builtoutputsfile $source\obj\IntegrityService.Installer.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile $source\IntegrityService.Installer\IntegrityService.Installer.wixproj -pedantic -v

      - name: Generate hashes
        shell: powershell
        run: Get-ChildItem -Path "D:\a\IntegrityService\IntegrityService\publish" -File | ForEach-Object { $hash = Get-FileHash -Path $_.FullName -Algorithm SHA256; $line= "(SHA256)`t$($hash.Hash)`t$($_.Name)"; $line | Out-File -FilePath D:\a\IntegrityService\IntegrityService\publish\hashes.txt -Append -Encoding unicode -NoClobber }

      - name: Enumerate root folder
        shell: powershell
        run: ls -r

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            D:\a\IntegrityService\IntegrityService\publish\IntegrityService.exe
            D:\a\IntegrityService\IntegrityService\publish\IntegrityService.Installer.msi
            D:\a\IntegrityService\IntegrityService\publish\hashes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
