name: Release when tagged

on:
  workflow_dispatch:

  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.ADML'
      - '**.ADMX'
      - '**.ico'
      - '**.reg'
      - '**.yml'
    tags:
      - "*.*.*"

  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.ADML'
      - '**.ADMX'
      - '**.ico'
      - '**.reg'
      - '**.yml'
jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Wix
        uses: actions/checkout@v4
        with:
          repository: fbarresi/wix
          path: wix

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Restore and publish main project
        run: msbuild IntegrityService\IntegrityService.csproj /t:restore /t:publish /p:Configuration=Release /p:SelfContained=true /p:RuntimeIdentifier=win-x64 /p:PublishsingleFile=true

      - name: Create a publish directory
        run: mkdir D:\a\IntegrityService\IntegrityService\publish
        
      - name: Copy executable there
        run: Copy-Item -Path D:\a\IntegrityService\IntegrityService\IntegrityService\bin\Release\net8.0-windows10.0.17763.0\win-x64\IntegrityService.exe -Destination D:\a\IntegrityService\IntegrityService\publish\ -Verbose

      - name: Enumerate root folder
        shell: powershell
        run: ls -r

      - name: Build installer
        run: |
          cd IntegrityService.Installer
          wix extension add WixToolset.Util.wixext/5.0.0
          wix extension list
          wix build -arch x64 -ext ./publish/.wix/extensions/WixToolset.Util.wixext/5.0.0/wixext5/WixToolset.Util.wixext.dll -pdbtype none -i publish -o ./publish/IntegrityService.msi IntegrityService.Installer/Product.wxs

      - name: Generate hashes
        shell: powershell
        run: Get-ChildItem -Path "D:\a\IntegrityService\IntegrityService\publish" -File | ForEach-Object { $hash = Get-FileHash -Path $_.FullName -Algorithm SHA256; $line= "(SHA256)`t$($hash.Hash)`t$($_.Name)"; $line | Out-File -FilePath D:\a\IntegrityService\IntegrityService\publish\hashes.txt -Append -Encoding unicode -NoClobber }

      - name: Enumerate root folder
        shell: powershell
        run: ls -r

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            D:\a\IntegrityService\IntegrityService\publish\IntegrityService.exe
            D:\a\IntegrityService\IntegrityService\publish\IntegrityService.Installer.msi
            D:\a\IntegrityService\IntegrityService\publish\hashes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
