name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
  
    - name: Restore and publish
      run: msbuild IntegrityService.sln /t:restore /t:publish /p:Configuration=Release /p:SelfContained=true /p:RuntimeIdentifier=win-x64 /p:PublishsingleFile=true

    - name: Enumerate root folder
      shell: powershell
      run: ls
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "alpha"
        generate_release_notes: true
        files: .\IntegrityService\bin\Release\net6.0-windows\win-x64\publish\IntegrityService.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
